import * as maplibregl from "maplibre-gl";
import type { MapMouseEvent } from "maplibre-gl";
import { useEffect, useRef } from "react";
import type { Region, RegionCode } from "@/features/data/types";
export default function RegionMap({ regions, selected, onSelect }: {regions:Region[];selected:RegionCode;onSelect:(code:RegionCode)=>void}) {
 const el=useRef<HTMLDivElement>(null); const map=useRef<maplibregl.Map|null>(null);
 useEffect(()=>{ if(!el.current||map.current) return; const instance=new maplibregl.Map({container:el.current,style:{version:8,sources:{},layers:[{id:"background",type:"background",paint:{"background-color":"#07131b"}}]},center:[79.5,20],zoom:3.35,attributionControl:false});
 instance.on("load",()=>{ instance.addSource("regions",{type:"geojson",data:{type:"FeatureCollection",features:regions.map(r=>({type:"Feature",properties:{code:r.code,name:r.name},geometry:{type:"Point",coordinates:[r.lon,r.lat]}}))}}); instance.addLayer({id:"region-rings",type:"circle",source:"regions",paint:{"circle-radius":["case",["==",["get","code"],selected],18,11],"circle-color":["case",["==",["get","code"],selected],"#45e6d3","#f5b54c"],"circle-opacity":.22,"circle-stroke-width":2,"circle-stroke-color":["case",["==",["get","code"],selected],"#45e6d3","#f5b54c"]}}); instance.addLayer({id:"region-labels",type:"symbol",source:"regions",layout:{"text-field":["get","code"],"text-size":12,"text-offset":[0,2]},paint:{"text-color":"#e9f7f8","text-halo-color":"#07131b","text-halo-width":2}}); instance.on("click","region-rings",(e: MapMouseEvent & {features?: Array<{properties?: {code?: unknown}}>})=>{const code=e.features?.[0]?.properties?.code;if(code === "KWG" || code === "BOB" || code === "IGP")onSelect(code)}); instance.on("mouseenter","region-rings",()=>instance.getCanvas().style.cursor="pointer"); instance.on("mouseleave","region-rings",()=>instance.getCanvas().style.cursor=""); }); map.current=instance; return()=>{instance.remove();map.current=null}; },[regions,onSelect,selected]);
 useEffect(()=>{const instance=map.current;if(instance?.getLayer("region-rings")) instance.setPaintProperty("region-rings","circle-radius",["case",["==",["get","code"],selected],18,11]);},[selected]);
 return <div className="region-map" ref={el} aria-label="Map of SkillBlend pilot regions"/>;
}
