/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as WeightsRouteImport } from './routes/weights'
import { Route as ReplayEventIdRouteImport } from './routes/replay.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightsRoute = WeightsRouteImport.update({
  id: '/weights',
  path: '/weights',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayEventIdRoute = ReplayEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => ReplayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/replay': typeof ReplayRouteWithChildren
  '/weights': typeof WeightsRoute
  '/replay/$eventId': typeof ReplayEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/replay': typeof ReplayRouteWithChildren
  '/weights': typeof WeightsRoute
  '/replay/$eventId': typeof ReplayEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/replay': typeof ReplayRouteWithChildren
  '/weights': typeof WeightsRoute
  '/replay/$eventId': typeof ReplayEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forecast' | '/replay' | '/weights' | '/replay/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forecast' | '/replay' | '/weights' | '/replay/$eventId'
  id:
    '__root__' | '/' | '/forecast' | '/replay' | '/weights' | '/replay/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForecastRoute: typeof ForecastRoute
  ReplayRoute: typeof ReplayRouteWithChildren
  WeightsRoute: typeof WeightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weights': {
      id: '/weights'
      path: '/weights'
      fullPath: '/weights'
      preLoaderRoute: typeof WeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay/$eventId': {
      id: '/replay/$eventId'
      path: '/$eventId'
      fullPath: '/replay/$eventId'
      preLoaderRoute: typeof ReplayEventIdRouteImport
      parentRoute: typeof ReplayRoute
    }
  }
}

interface ReplayRouteChildren {
  ReplayEventIdRoute: typeof ReplayEventIdRoute
}

const ReplayRouteChildren: ReplayRouteChildren = {
  ReplayEventIdRoute: ReplayEventIdRoute,
}

const ReplayRouteWithChildren =
  ReplayRoute._addFileChildren(ReplayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForecastRoute: ForecastRoute,
  ReplayRoute: ReplayRouteWithChildren,
  WeightsRoute: WeightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
